-- Luku vocabulary schema
-- Run this in the Neon SQL editor once after enabling Neon Auth.
-- Neon Auth automatically populates neon_auth.users_sync.

CREATE TABLE IF NOT EXISTS words (
  id             SERIAL PRIMARY KEY,
  user_id        TEXT NOT NULL,            -- from Neon Auth (Stack Auth user ID)
  base           TEXT NOT NULL,            -- dictionary base form (the main memorization unit)
  translations   TEXT[] NOT NULL,          -- English translations of the base form, primary first
  pos            TEXT NOT NULL DEFAULT 'other', -- noun/verb/adjective/adverb/other
  forms          JSONB NOT NULL DEFAULT '[]', -- scanned inflections: [{"word": "...", "translation": "..."}]

  -- Optional example sentence and its English translation (null until generated)
  example            TEXT,
  example_translation TEXT,

  -- SRS fields (SM-2)
  ease_factor    FLOAT NOT NULL DEFAULT 2.5,
  interval_days  INT   NOT NULL DEFAULT 0,
  review_count   INT   NOT NULL DEFAULT 0,
  next_review_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  added_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, base)
);

CREATE INDEX IF NOT EXISTS words_user_due ON words (user_id, next_review_at);

-- Migration for deployments created before the forms column existed.
-- Seeds forms from the previously saved inflection; its old translations
-- were contextual, so the first one doubles as the form translation.
-- Wrapped in an existence check so fresh installs (which never had a word
-- column) don't trip on the UPDATE referencing it.
ALTER TABLE words ADD COLUMN IF NOT EXISTS forms JSONB NOT NULL DEFAULT '[]';
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'words' AND column_name = 'word'
  ) THEN
    UPDATE words
      SET forms = jsonb_build_array(jsonb_build_object('word', word, 'translation', translations[1]))
      WHERE forms = '[]'::jsonb AND lower(word) <> lower(base);
  END IF;
END $$;

-- The word column is now redundant: every inflection lives in forms.
ALTER TABLE words DROP COLUMN IF EXISTS word;

-- Migration: add example sentence columns (null until generated by a follow-up).
ALTER TABLE words ADD COLUMN IF NOT EXISTS example TEXT;
ALTER TABLE words ADD COLUMN IF NOT EXISTS example_translation TEXT;

-- ── Telegram bot ─────────────────────────────────────────────────────────────
-- Binds a Telegram account to a Luku account so the bot can run review
-- sessions and send reminders. The webhook secret is what authenticates
-- Telegram itself; telegram_user_id is only a lookup key.

CREATE TABLE IF NOT EXISTS telegram_links (
  telegram_user_id  BIGINT PRIMARY KEY,
  user_id           TEXT NOT NULL,             -- from Neon Auth (Stack Auth user ID)
  chat_id           BIGINT NOT NULL,
  username          TEXT,
  secret_hash       TEXT NOT NULL,             -- reserved for a future second channel (Mini App / magic link)
  reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  reminder_hour     SMALLINT NOT NULL DEFAULT 9,  -- 0-23, in the user's local time
  timezone          TEXT NOT NULL DEFAULT 'Europe/Helsinki',
  last_reminded_on  DATE,                      -- local date; keeps the hourly cron idempotent
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at      TIMESTAMPTZ
);

-- One Telegram account per Luku account and vice versa.
CREATE UNIQUE INDEX IF NOT EXISTS telegram_links_user ON telegram_links (user_id);

-- One-time codes backing the t.me/<bot>?start=<code> deep link.
-- Only the hash is stored: the nightly pg_dump would otherwise carry live
-- bearer tokens for as long as backups are retained.
CREATE TABLE IF NOT EXISTS telegram_link_codes (
  code_hash   TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS telegram_link_codes_user ON telegram_link_codes (user_id);

-- At most one claimable code per user, enforced here rather than by a
-- delete-then-insert pair: the HTTP driver has no transactions, so two
-- concurrent mint requests could otherwise both delete before either inserted
-- and leave two redeemable deep links. Drop any duplicates a pre-index
-- deployment accumulated before adding the constraint.
DELETE FROM telegram_link_codes a
  USING telegram_link_codes b
  WHERE a.user_id = b.user_id
    AND a.used_at IS NULL AND b.used_at IS NULL
    AND (a.created_at, a.code_hash) < (b.created_at, b.code_hash);

CREATE UNIQUE INDEX IF NOT EXISTS telegram_link_codes_active
  ON telegram_link_codes (user_id) WHERE used_at IS NULL;
