name: luku-prod-backup

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 05:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  db-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Backup Postgres to B2
        uses: cy6erskunk/pg-b2-backup@290257aea345b85f549f188b1d6d759558908e6c
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          b2-application-key-id: ${{ secrets.B2_APPLICATION_KEY_ID }}
          b2-application-key: ${{ secrets.B2_APPLICATION_KEY }}
          b2-bucket-name: ${{ secrets.B2_BUCKET_NAME }}
          b2-region: "eu-central-003"
          folder-name: "luku-prod-backup"
          retention-days: "7"
          pg-version: "16"
